#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: demo-application-dev
#  namespace: argocd
#spec:
#  project: default
#  source:
#    repoURL: 'https://github.com/jrdegroot/demo-application-deployment.git'
#    targetRevision: HEAD
#    path: .
#    helm:
#      valueFiles:
#        - dev.yaml
#  destination:
#    server: https://kubernetes.default.svc
#    namespace: demo
#
#  syncPolicy:
#    syncOptions:
#      - CreateNamespace=true
#    automated:
#      selfHeal: true
#      prune: true
