apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.label" . }}-ingress
spec:
  rules:
    - host: demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.label" . }}-service
                port:
                  number: 8080
